#!/usr/bin/env bash
set -e

vault_name=$1
secret=$2

if [ -z "$vault_name" ] || [ -z "$secret" ]; then
  echo "Usage: $0 <vault-name> <secret-name>" >&2
  exit 1
fi

if ! az account show > /dev/null 2>&1; then
  echo "You are not logged in. Please run 'az login'." >&2
fi

az keyvault secret show --vault-name "${vault_name}" --name "${secret}" --query "value" -o tsv

#if [ -z "$value" ]; then
#  echo "Error: Secret not found or you don't have access." >&2
#  exit 2
#fi
#
#echo $value
