#!/usr/bin/env bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

vault=$1
secret=$2

if [ -z "$vault" ]; then
  vault=$("$SCRIPT_DIR/list-vaults" | fzf --prompt "Choose vault: ")
  if [ -n "$vault" ]; then
    echo "vault = '$vault'" >&2
  else
    echo "err: You need to select a vault" >&2
    exit 1
  fi
fi

if [ -z "$secret"]; then
  secret=$("$SCRIPT_DIR/list-secrets" $vault | fzf --prompt "Choose secret: ")
  if [ -n "$secret" ]; then
    echo "secret = '$secret'" >&2
  else
    echo "err: You need to select a vault" >&2
    exit 2
  fi
fi

$SCRIPT_DIR/get-secret $vault $secret
