#!/usr/bin/env bash
set -e

if ! az account show > /dev/null 2>&1; then
  echo "You are not logged in. Please run 'az login'." >&2
fi

json=$(az account list --query '[].{name:name, subscriptionId:id, tenantId:tenantId}' -o json)

echo $json | jq > /dev/null 2>&1 
if [ $? -ne 0 ]; then 
  echo "Could not fetch vaults" >&2
fi

echo $json | jq -r '.[] | "\(.subscriptionId) \(.name)"'
