#!/usr/bin/env bash
set -e

vault_name=$1

if [ -z "$vault_name" ]; then
  echo "Usage: $0 <vault-name>" >&2
  exit 1
fi

if ! az account show > /dev/null 2>&1; then
  echo "You are not logged in. Please run 'az login'." >&2
fi

json=$(az keyvault secret list --vault-name ${vault_name} --query "[].name" --output json)

echo $json | jq > /dev/null 2>&1 
if [ $? -ne 0 ]; then 
  echo "Could not fetch vaults" >&2
fi

echo $json | jq -r '.[]' 
