#!/usr/bin/env bash
set -e

sub_id=$1

if [ -z "$sub_id" ]; then
  echo "Usage: $0 <subscriptionId>" >&2
  exit 1
fi

if ! az account show > /dev/null 2>&1; then
  echo "You are not logged in. Please run 'az login'." >&2
fi

az account set --subscription "$sub_id"
